### PR TITLE
Added GNU+Linux compatibility.

### PR DESCRIPTION
**Pull request by MiggL**
However, there are NO HOTKEY FUNCTIONS on GNU+Linux.

Compilation on windows should not be affected, but has not been tested.

I have mostly just added a bunch of "#ifdef Q_OS_WIN" to make the compiler ignore windows specific code on GNU+Linux.
As you propably know, the hotkey functions use windows specific code.

Please discuss these changes so the software can be improved.

### CODE REVIEW

**Comment by farpenoodle** [comment]
Thanks for this. I don't have a system/vm running desktop linux at the moment so I can't test. However I assume it should work. If QT hotkey system works across linux unlike windows then we shouldn't need to roll some kind of keyboard poller for linux.

**Comment by lorddrachenblut** [comment]
Thank you both for your awesome work.

**Comment by ajclarke** [comment]
Compiles fine for me too on Linux, though I've also added a comment to the first commit.

I'm wondering though @farpenoodle  - what was the reason for using windows events (windows_generic_MSG) for handling keyboard input originally?

**Comment by farpenoodle** [comment]
In order to use hotkeys in certain games you need to poll keyboard input. OBS uses a similar setup to do hotkeys.

**Comment by MiggL** [comment]
Hmmm I think I have managed to add hotkey support for GNU+Linux and Mac OS X, basically using c3r1c3's code. Is there any documentation on how the hotkey functionality should work? Only one I know is saving with Ctrl + s.

**Pull request merged**
